# Generated by Django 4.2.3 on 2023-08-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditek', '0002_ciclo_trabajo_fecha_control_value_fecha_estado_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
    ]
