# Generated by Django 4.2.3 on 2023-08-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditek', '0003_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasenia',
        ),
    ]
