# Generated by Django 4.2.3 on 2023-08-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditek', '0004_rename_contraseña_usuario_contrasenia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
